apex: true
apex_opt_level: O1
average_clips: score
dataset:
  ood_test:
    fold: 1
    name: hmdb51
    split: test-split{fold}
    subset: test-k400
  ood_type: new
  test:
    aug_mode: val
    batch_size: 32
    clip_duration: 2
    clips_per_video: 5
    crop_size: 112
    fold: 1
    mode: video
    name: kinetics400
    split: val
    vid_aug_kwargs:
      normalize: true
      pad_missing: true
      totensor: true
    vid_transform: randaug3crop
    video_fps: 8.0
  train:
    aug_mode: train
    batch_size: 512
    clip_duration: 2
    clips_per_video: 1
    crop_size: 112
    drop_last: true
    fold: 1
    mode: clip
    name: kinetics400
    split: train
    use_shuffle: true
    vid_aug_kwargs:
      aspect_ratio:
      - 0.75
      - 1.3333
      auto_augment: rand-m7-n4-mstd0.5-inc1
      hflip: true
      min_area:
      - 0.2
      - 0.766
      normalize: true
      pad_missing: true
      rand_erase:
        max_count: 1
        mode: pixel
        num_splits: 1
        probability: 0.25
      totensor: true
    vid_transform: randaug3crop
    video_fps: 8.0
eval_freq: 10
evidence: exp
hyperparams:
  criterion:
    kwargs:
      annealing_method: exp
      evidence: exp
      loss_type: log
      with_avuloss: false
      with_kldiv: false
    name: dear
  layer_decay: 0.55
  lr:
    base_lr: 0.0005
    final_lr: 1.0e-06
    name: cosine
    warmup_epochs: 10
    warmup_lr: 1.0e-06
  num_epochs: 100
  optimizer:
    betas:
    - 0.9
    - 0.999
    momentum: 0.9
    name: adamw
    weight_decay: 0.05
model:
  apply_debias_head: false
  classifier:
    dropout: 0.5
    l2_norm: false
    num_classes: 400
    use_bn: false
    use_dropout: true
  debias_head:
    dropout_ratio: 0.5
    head_hidden_dim: 2048
    init_std: 0.01
    loss_factor: 0.1
  fwd_kwargs:
    feat_op: pool
  vid_backbone:
    apply_cls_token: true
    drop_path_rate: 0
    drop_rate: 0
    frame_size:
    - 3
    - 112
    - 112
    num_frames: 16
    patch_spatial:
    - 16
    - 16
    patch_temporal: 4
    vit_config: base
  vid_setup: finetune
name: k400-open-set
num_workers: 32
progress:
  log2tb: false
  print_freq: 10
  wandb: true
sync_bn: true
uncertainty: EDL
