apex: true
apex_opt_level: O1
average_clips: score
dataset:
  ood_test:
    fold: 1
    name: hmdb51
    split: test-split{fold}
    subset: test-u101
  ood_type: new
  test:
    aug_mode: val
    batch_size: 32
    clip_duration: 2
    clips_per_video: 5
    crop_size: 112
    fold: 1
    mode: video
    name: ucf101
    split: testlist{fold:02d}
    vid_aug_kwargs:
      normalize: true
      pad_missing: true
      totensor: true
    vid_transform: strong3crop
    video_fps: 8.0
  train:
    aug_mode: train
    batch_size: 1024
    clip_duration: 2
    clips_per_video: 5
    crop_size: 112
    drop_last: true
    fold: 1
    mode: clip
    name: ucf101
    split: trainlist{fold:02d}
    use_shuffle: true
    vid_aug_kwargs:
      color:
      - 0.4
      - 0.4
      - 0.4
      - 0.2
      min_area:
      - 0.2
      - 0.766
      normalize: true
      p_blur: 0.0
      p_flip: 0.5
      p_gray: 0.2
      pad_missing: true
      totensor: true
    vid_transform: strong3crop
    video_fps: 8.0
eval_freq: 5
evidence: exp
hyperparams:
  criterion:
    kwargs:
      annealing_method: exp
      evidence: exp
      loss_type: log
      with_avuloss: false
      with_kldiv: false
    name: dear
  layer_decay: 1
  lr:
    base_lr: 0.006
    final_lr: 0.0
    name: cosine
    warmup_epochs: 10
    warmup_lr: 0.0
  num_epochs: 100
  optimizer:
    betas:
    - 0.9
    - 0.999
    momentum: 0.9
    name: adamw
    weight_decay: 0.0
model:
  apply_debias_head: false
  classifier:
    dropout: 0.0
    l2_norm: false
    num_classes: 101
    use_bn: false
    use_dropout: true
  debias_head:
    dropout_ratio: 0.5
    head_hidden_dim: 2048
    init_std: 0.01
    loss_factor: 0.1
  fwd_kwargs:
    feat_op: pool
  vid_backbone:
    apply_cls_token: true
    drop_path_rate: 0
    drop_rate: 0
    frame_size:
    - 3
    - 112
    - 112
    num_frames: 16
    patch_spatial:
    - 16
    - 16
    patch_temporal: 4
    vit_config: base
  vid_setup: linear
name: u101-open-set
num_workers: 32
progress:
  log2tb: false
  print_freq: 10
  wandb: true
sync_bn: true
uncertainty: EDL
