apex: true
apex_opt_level: O1
dataset:
  batch_size: 32
  clip_duration: 2
  crop_size: 112
  name: mitv2
  ood_test:
    aug_mode: val
    clips_per_video: 2
    drop_last: false
    mode: video
    name: tinyvirat
    split: val
    subset: mitv2
    use_shuffle: false
    vid_aug_kwargs:
      normalize: true
      pad_missing: true
      totensor: true
  return_audio: false
  return_video: true
  test:
    aug_mode: val
    clips_per_video: 2
    drop_last: false
    mode: video
    split: val
    subset: tinyvirat
    use_shuffle: false
    vid_aug_kwargs:
      normalize: true
      pad_missing: true
      totensor: true
  train:
    aug_mode: train
    clips_per_video: 5
    drop_last: true
    mode: clip
    split: train
    subset: tinyvirat
    use_shuffle: true
    vid_aug_kwargs:
      color:
      - 0.4
      - 0.4
      - 0.4
      - 0.2
      min_area:
      - 0.2
      - 0.766
      normalize: true
      p_blur: 0.0
      p_flip: 0.5
      p_gray: 0.2
      pad_missing: true
      totensor: true
  vid_transform: strong3crop
  video_fps: 8.0
hyperparams:
  lr:
    base_lr: 4.0e-05
    final_lr: 0
    gamma: 0
    milestones: []
    name: cosine
    warmup_epochs: 20
    warmup_lr: 0
  num_epochs: 100
  optimizer:
    momentum: 0.9
    name: sgd
    weight_decay: 1.0e-05
model:
  backbone:
    apply_cls_token: true
    frame_size:
    - 3
    - 112
    - 112
    num_frames: 32
    patch_spatial:
    - 16
    - 16
    patch_temporal: 4
    vit_config: base
  classifier:
    dropout: 0
    l2_norm: false
    num_classes: 14
    use_bn: true
    use_dropout: false
  ensemble: mean
  fwd_kwargs:
    feat_op: pool
num_workers: 16
progress:
  log2tb: false
  print_freq: 10
  wandb: false
sync_bn: true
