apex: true
apex_opt_level: O1
dataset:
  batch_size: 768
  clip_duration: 2
  crop_size: 112
  fold: 1
  name: charadesego_text
  ood_test:
    aug_mode: val
    clips_per_video: 20
    drop_last: false
    mode: video
    name: charadesego_text
    split: val
    subset: test_1st
    use_shuffle: false
    vid_aug_kwargs:
      normalize: true
      pad_missing: true
      totensor: true
  return_audio: false
  return_video: true
  test:
    aug_mode: val
    clips_per_video: 20
    drop_last: false
    mode: video
    split: val
    subset: test_3rd
    use_shuffle: false
    vid_aug_kwargs:
      normalize: true
      pad_missing: true
      totensor: true
  train:
    aug_mode: train
    clips_per_video: 1
    drop_last: true
    mode: clip
    split: train
    subset: train_3rd
    use_shuffle: true
    vid_aug_kwargs:
      color:
      - 0.4
      - 0.4
      - 0.4
      - 0.2
      min_area:
      - 0.2
      - 0.766
      normalize: true
      p_blur: 0.0
      p_flip: 0.5
      p_gray: 0.2
      pad_missing: true
      totensor: true
  vid_transform: strong3crop
  video_fps: 8.0
eval_freq: 1
hyperparams:
  cutmix: 0.0
  cutmix_minmax: null
  label_smoothing: 0.0
  layer_decay: 0.55
  lr:
    base_lr: 0.0005
    final_lr: 0
    name: cosine
    warmup_epochs: 5
    warmup_lr: 0
  mixup: 0.0
  mixup_mode: batch
  mixup_prob: 1.0
  mixup_switch_prob: 0.5
  num_epochs: 20
  optimizer:
    betas:
    - 0.9
    - 0.999
    name: adamw
  weight_decay: 0
model:
  ensemble: mean
  fwd_kwargs:
    feat_op: pool
  text_encoder:
    name: distilbert
  vid_backbone:
    apply_cls_token: true
    drop_path_rate: 0
    drop_rate: 0
    frame_size:
    - 3
    - 112
    - 112
    num_frames: 32
    patch_spatial:
    - 16
    - 16
    patch_temporal: 4
    vit_config: base
  vid_setup: linear
name: charadesego-linear
num_workers: 32
progress:
  log2tb: false
  print_freq: 10
  wandb: true
sync_bn: true
